# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\softwareApuraçãoCarnavalLogicaFuzzy\novaApuração.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaginaInicial(object):
    def setupUi(self, PaginaInicial):
        PaginaInicial.setObjectName("PaginaInicial")
        PaginaInicial.resize(1032, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaginaInicial.sizePolicy().hasHeightForWidth())
        PaginaInicial.setSizePolicy(sizePolicy)
        PaginaInicial.setMinimumSize(QtCore.QSize(1032, 555))
        PaginaInicial.setMaximumSize(QtCore.QSize(1032, 555))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/paginaIncial/iconeJanela.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PaginaInicial.setWindowIcon(icon)
        PaginaInicial.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(parent=PaginaInicial)
        self.centralwidget.setObjectName("centralwidget")
        self.botaoVoltar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoVoltar.setGeometry(QtCore.QRect(70, 450, 281, 81))
        self.botaoVoltar.setStyleSheet("QPushButton{\n"
"color: rgb(170, 170, 255);\n"
"background-color: rgb(255, 255, 0);\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 255, 127);\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.botaoVoltar.setObjectName("botaoVoltar")
        self.botaoApurar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoApurar.setGeometry(QtCore.QRect(600, 280, 321, 81))
        self.botaoApurar.setStyleSheet("QPushButton{\n"
"color: rgb(231, 121, 41);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.botaoApurar.setObjectName("botaoApurar")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -200, 1731, 961))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/novaApuração/background.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 120, 201, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 15px\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(260, 180, 301, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 15px\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.boxComissao = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.boxComissao.setGeometry(QtCore.QRect(110, 130, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.boxComissao.setFont(font)
        self.boxComissao.setMaximum(10)
        self.boxComissao.setProperty("value", 5)
        self.boxComissao.setObjectName("boxComissao")
        self.boxHarmonia = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.boxHarmonia.setGeometry(QtCore.QRect(110, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxHarmonia.setFont(font)
        self.boxHarmonia.setMaximum(10)
        self.boxHarmonia.setProperty("value", 5)
        self.boxHarmonia.setObjectName("boxHarmonia")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 250, 301, 41))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 15px\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setGeometry(QtCore.QRect(260, 320, 301, 41))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 15px\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.boxEnredo = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.boxEnredo.setGeometry(QtCore.QRect(110, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxEnredo.setFont(font)
        self.boxEnredo.setMaximum(10)
        self.boxEnredo.setProperty("value", 5)
        self.boxEnredo.setObjectName("boxEnredo")
        self.boxEvolucao = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.boxEvolucao.setGeometry(QtCore.QRect(110, 330, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxEvolucao.setFont(font)
        self.boxEvolucao.setMaximum(10)
        self.boxEvolucao.setProperty("value", 5)
        self.boxEvolucao.setObjectName("boxEvolucao")
        self.boxEscola = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.boxEscola.setGeometry(QtCore.QRect(610, 120, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxEscola.setFont(font)
        self.boxEscola.setPlainText("")
        self.boxEscola.setObjectName("boxEscola")
        self.boxAno = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.boxAno.setGeometry(QtCore.QRect(610, 180, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxAno.setFont(font)
        self.boxAno.setPlainText("")
        self.boxAno.setObjectName("boxAno")
        self.boxSenha = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.boxSenha.setGeometry(QtCore.QRect(610, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxSenha.setFont(font)
        self.boxSenha.setPlainText("")
        self.boxSenha.setObjectName("boxSenha")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(920, 230, 81, 51))
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(255, 0, 0);\n"
"    font: 75 28pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_3.raise_()
        self.botaoVoltar.raise_()
        self.pushButton_3.raise_()
        self.pushButton_7.raise_()
        self.boxHarmonia.raise_()
        self.pushButton_9.raise_()
        self.pushButton_11.raise_()
        self.boxEnredo.raise_()
        self.boxEvolucao.raise_()
        self.boxEscola.raise_()
        self.boxAno.raise_()
        self.boxComissao.raise_()
        self.botaoApurar.raise_()
        self.boxSenha.raise_()
        self.label_4.raise_()
        PaginaInicial.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaginaInicial)
        QtCore.QMetaObject.connectSlotsByName(PaginaInicial)

    def retranslateUi(self, PaginaInicial):
        _translate = QtCore.QCoreApplication.translate
        PaginaInicial.setWindowTitle(_translate("PaginaInicial", "Apurador Carnavalesco"))
        self.botaoVoltar.setText(_translate("PaginaInicial", "Voltar"))
        self.botaoApurar.setText(_translate("PaginaInicial", "Apurar"))
        self.pushButton_3.setText(_translate("PaginaInicial", "Comissão de frente"))
        self.pushButton_7.setText(_translate("PaginaInicial", "Harmonia"))
        self.pushButton_9.setText(_translate("PaginaInicial", "Enredo"))
        self.pushButton_11.setText(_translate("PaginaInicial", "Evolução"))
        self.boxEscola.setPlaceholderText(_translate("PaginaInicial", "Escola"))
        self.boxAno.setPlaceholderText(_translate("PaginaInicial", "Ano"))
        self.boxSenha.setPlaceholderText(_translate("PaginaInicial", "Senha"))
        self.label_4.setText(_translate("PaginaInicial", "*"))
