# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\softwareApuraçãoCarnavalLogicaFuzzy\paginaHistorico.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaginaInicial(object):
    def setupUi(self, PaginaInicial):
        PaginaInicial.setObjectName("PaginaInicial")
        PaginaInicial.resize(1032, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaginaInicial.sizePolicy().hasHeightForWidth())
        PaginaInicial.setSizePolicy(sizePolicy)
        PaginaInicial.setMinimumSize(QtCore.QSize(1030, 555))
        PaginaInicial.setMaximumSize(QtCore.QSize(1032, 555))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/paginaIncial/iconeJanela.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PaginaInicial.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=PaginaInicial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1032, 555))
        self.centralwidget.setMaximumSize(QtCore.QSize(1032, 555))
        self.centralwidget.setObjectName("centralwidget")
        self.botaoVoltar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoVoltar.setGeometry(QtCore.QRect(130, 490, 291, 51))
        self.botaoVoltar.setStyleSheet("QPushButton{\n"
"color: rgb(0, 85, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 0, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.botaoVoltar.setObjectName("botaoVoltar")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -110, 1081, 781))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/Histórico/background.png"))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(140, 160, 751, 291))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.caixaDeTexto = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.caixaDeTexto.setEnabled(False)
        self.caixaDeTexto.setGeometry(QtCore.QRect(0, 0, 751, 291))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.caixaDeTexto.setFont(font)
        self.caixaDeTexto.setObjectName("caixaDeTexto")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.caixaSenha = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.caixaSenha.setGeometry(QtCore.QRect(450, 500, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.caixaSenha.setFont(font)
        self.caixaSenha.setObjectName("caixaSenha")
        self.botaoIr = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botaoIr.setGeometry(QtCore.QRect(810, 500, 93, 31))
        self.botaoIr.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"    font: 87 9pt \"Arial Black\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"    font: 87 9pt \"Arial Black\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.botaoIr.setObjectName("botaoIr")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 140, 741, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(0, 0, 0);\n"
"    font: 87 10pt \"Arial Black\";\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.botaoVoltar.raise_()
        self.scrollArea.raise_()
        self.caixaSenha.raise_()
        self.botaoIr.raise_()
        self.label_2.raise_()
        PaginaInicial.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaginaInicial)
        QtCore.QMetaObject.connectSlotsByName(PaginaInicial)

    def retranslateUi(self, PaginaInicial):
        _translate = QtCore.QCoreApplication.translate
        PaginaInicial.setWindowTitle(_translate("PaginaInicial", "Apurador Carnavalesco"))
        self.botaoVoltar.setText(_translate("PaginaInicial", "Voltar"))
        self.caixaSenha.setPlaceholderText(_translate("PaginaInicial", "Senha *"))
        self.botaoIr.setText(_translate("PaginaInicial", "Ir"))
        self.label_2.setText(_translate("PaginaInicial", "ID                   -      Escola               -        Ano               -               Conceito final"))
