# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\softwareApuraçãoCarnavalLogicaFuzzy\paginaInicial.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaginaInicial(object):
    def setupUi(self, PaginaInicial):
        PaginaInicial.setObjectName("PaginaInicial")
        PaginaInicial.resize(1032, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaginaInicial.sizePolicy().hasHeightForWidth())
        PaginaInicial.setSizePolicy(sizePolicy)
        PaginaInicial.setMinimumSize(QtCore.QSize(1030, 555))
        PaginaInicial.setMaximumSize(QtCore.QSize(1032, 555))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/paginaIncial/iconeJanela.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PaginaInicial.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=PaginaInicial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1032, 555))
        self.centralwidget.setMaximumSize(QtCore.QSize(1032, 555))
        self.centralwidget.setObjectName("centralwidget")
        self.novaApuracaoBotao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.novaApuracaoBotao.setGeometry(QtCore.QRect(310, 300, 411, 81))
        self.novaApuracaoBotao.setStyleSheet("QPushButton{\n"
"color: rgb(0, 85, 255);\n"
"background-color: rgb(255, 85, 255);\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 0, 255);\n"
"background-color: rgb(255, 255, 0);\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.novaApuracaoBotao.setObjectName("novaApuracaoBotao")
        self.historicoBotao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.historicoBotao.setGeometry(QtCore.QRect(310, 390, 411, 81))
        self.historicoBotao.setStyleSheet("QPushButton{\n"
"color: rgb(231, 121, 41);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(85, 170, 255);\n"
"background-color: rgb(85, 0, 255);\n"
"font: 22pt \"MV Boli\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.historicoBotao.setObjectName("historicoBotao")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -60, 1091, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/paginaIncial/background.png"))
        self.label.setObjectName("label")
        self.Sobre = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Sobre.setGeometry(QtCore.QRect(840, 20, 171, 41))
        self.Sobre.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 255);\n"
"    font: 15pt \"MV Boli\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(170, 0, 127);\n"
"    font: 20pt \"MV Boli\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"}")
        self.Sobre.setObjectName("Sobre")
        self.label.raise_()
        self.novaApuracaoBotao.raise_()
        self.historicoBotao.raise_()
        self.Sobre.raise_()
        PaginaInicial.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaginaInicial)
        QtCore.QMetaObject.connectSlotsByName(PaginaInicial)

    def retranslateUi(self, PaginaInicial):
        _translate = QtCore.QCoreApplication.translate
        PaginaInicial.setWindowTitle(_translate("PaginaInicial", "Apurador Carnavalesco"))
        self.novaApuracaoBotao.setText(_translate("PaginaInicial", "Nova Apuração"))
        self.historicoBotao.setText(_translate("PaginaInicial", "Histórico de Apurações"))
        self.Sobre.setText(_translate("PaginaInicial", "Sobre"))
