# Form implementation generated from reading ui file 'c:\Users\barba\Documents\vs\softwareApuraçãoCarnavalLogicaFuzzy\Sobre.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaginaInicial(object):
    def setupUi(self, PaginaInicial):
        PaginaInicial.setObjectName("PaginaInicial")
        PaginaInicial.resize(1032, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaginaInicial.sizePolicy().hasHeightForWidth())
        PaginaInicial.setSizePolicy(sizePolicy)
        PaginaInicial.setMinimumSize(QtCore.QSize(1030, 555))
        PaginaInicial.setMaximumSize(QtCore.QSize(1032, 555))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/paginaIncial/iconeJanela.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PaginaInicial.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=PaginaInicial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1032, 555))
        self.centralwidget.setMaximumSize(QtCore.QSize(1032, 555))
        self.centralwidget.setObjectName("centralwidget")
        self.voltarBotao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voltarBotao.setGeometry(QtCore.QRect(60, 430, 411, 81))
        self.voltarBotao.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"font: 63 32pt \"Bookman Old Style\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color:  qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.129353 rgba(255, 65, 0, 255), stop:0.492537 rgba(124, 93, 195, 255), stop:0.890547 rgba(0, 85, 179, 255));\n"
"font: 63 32pt \"Bookman Old Style\";\n"
"border: 4px solid black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.voltarBotao.setObjectName("voltarBotao")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -50, 1091, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\barba\\Documents\\vs\\softwareApuraçãoCarnavalLogicaFuzzy\\imagens/Sobre/background.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, -90, 321, 751))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    font: 70 14pt \"BIZ UDMincho\";\n"
"}")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.voltarBotao.raise_()
        self.label_2.raise_()
        PaginaInicial.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaginaInicial)
        QtCore.QMetaObject.connectSlotsByName(PaginaInicial)

    def retranslateUi(self, PaginaInicial):
        _translate = QtCore.QCoreApplication.translate
        PaginaInicial.setWindowTitle(_translate("PaginaInicial", "Apurador Carnavalesco"))
        self.voltarBotao.setText(_translate("PaginaInicial", "Voltar"))
        self.label_2.setText(_translate("PaginaInicial", "Esse programa foi feito usando linguagem Python com o auxílio das seguintes bibliotecas: PyQt6, MySQL Connector, Skfuzzy  e Numpy. O intuito deste projeto foi criar um apurador de votos para desfiles de Carnaval baseado na lógica Fuzzy. Tendo isso em vista, os quesitos harmonia, comissão de frente, enredo e evolução foram definidos como as variáveis, cada um com as tags \"bom\", \"medio\" e \"ruim\". Assim, foram necessárias 81 regras para o controlador e a função de pertinência triangular foi a escolhida para o projeto. Além do mais, o diferencial do programa é o armazenamento das apurações em um banco de dados MySQL."))
